// {
// 	title: "",
// 	items: [
// 		{
// 			title: "", 
// 			description: "", 
// 			href: "", 
// 			src: "", 
// 			alt: "", 
// 			nature: "", 
// 			date: "",
// 		},
// 	],
// },

export default [
	{
		title: "Automated detection of former field systems from airborne laser scanning data", 
		description: "Apport de l'intelligence artificielle et des données LiDAR pour extraire des formes agraires anciennes.", 
		href: "https://doi.org/10.1016/j.jag.2021.102563", 
		src: "/work/academique-dypa-publication/thumb.jpg", 
		alt: "Extrait de champs bombés sur LiDAR", 
		nature: "publication", 
		date: "Décembre 2021",
	},
	{
		title: "Unprecedented and ancient spatial data for assessing the effect of past changes on current floristic biodiversity", 
		description: "Poster sur mon sujet de thèse, présenté à l'occasion du congrès des doctorants de l'ED413. Prix du meilleur poster.", 
		href: "/work/academique-doctorat-poster/content.pdf", 
		src: "/work/academique-doctorat-poster/thumb.jpg", 
		alt: "Extrait du poster", 
		nature: "poster", 
		date: "Février 2021",
	},
	{
		title: "Revealing long-term physiological trajectories of grasslands from legacy B&W aerial photographs", 
		description: "Démonstration de faisabilité pour l'extraction des trajectoires temporelles de prairies à partir de produits aériens colorisés.", 
		href: "https://www.isprs-ann-photogramm-remote-sens-spatial-inf-sci.net/V-3-2020/549/2020/", 
		src: "/work/academia-phd-paper-2/thumb.jpg", 
		alt: "Exemple de restauration de cliché historique", 
		nature: "publication", 
		date: "Août 2020",
	},
	{
		title: "Deep learning for automatic colorization of legacy grayscale aerial photographs", 
		description: "Utilisation d'un réseau de neurones profond pour la colorisation automatique de photographies aériennes panchromatiques.", 
		href: "https://ieeexplore.ieee.org/document/9103274", 
		src: "/work/academia-phd-paper-1/thumb.jpg", 
		alt: "Exemple de colorisation de cliché historique", 
		nature: "publication", 
		date: "Mai 2020",
	},
	{
		title: "La colorisation de photographies aériennes anciennes", 
		description: "Article de vulgarisation sur la colorisation automatique des photographies aériennes panchromatiques.", 
		href: "https://zaeu-strasbourg.eu/wp-content/uploads/2020/03/N11_colorisation.pdf", 
		src: "/work/academia-zaeu/thumb.jpg", 
		alt: "Extrait de l'article", 
		nature: "publication", 
		date: "Mars 2020",
	},
	{
		title: "La Géographie de Ptolémée", 
		description: "Outil interactif pour l'analyse des alignements maritimes extraits à partir de la Géographie de Ptolémée.", 
		href: "https://poterekq.github.io/ptolemy/", 
		src: "/work/academia-ptolemy/thumb.jpg", 
		alt: "Carte réalisée à partir de la Géographie de Ptolémée", 
		nature: "carte web", 
		date: "Mai 2019",
	},
]