// {
// 	title: "",
// 	items: [
// 		{
// 			title: "", 
// 			description: "", 
// 			href: "", 
// 			src: "", 
// 			alt: "", 
// 			nature: "", 
// 			date: "",
// 		},
// 	],
// },

export default [
	{
		title: "Automated detection of former field systems from airborne laser scanning data", 
		description: "Apport de l'intelligence artificielle et des données LiDAR pour extraire des formes agraires anciennes.", 
		href: "https://doi.org/10.1016/j.jag.2021.102563", 
		src: "/images/thumbnails/academia-paper-3.jpg", 
		alt: "Champs bombés sur photographie aérienne et LiDAR", 
		nature: "publication", 
		date: "Décembre 2021",
	},
	{
		title: "Unprecedented and ancient spatial data for assessing the effect of past changes on current floristic biodiversity", 
		description: "Poster sur mon sujet de thèse, présenté à l'occasion du congrès des doctorants de l'ED413. Prix du meilleur poster.", 
		href: "https://mega.nz/file/rxBCGJAa#P6qJ6seD2GxqW9S1hvi03lljRazhJOaKQCW5CKpJt0U", 
		src: "/images/thumbnails/academia-poster-1.jpg", 
		alt: "Extrait du poster", 
		nature: "poster", 
		date: "Février 2021",
	},
	{
		title: "Revealing long-term physiological trajectories of grasslands from legacy B&W aerial photographs", 
		description: "Démonstration de faisabilité pour l'extraction des trajectoires temporelles de prairies à partir de produits aériens colorisés.", 
		href: "https://www.isprs-ann-photogramm-remote-sens-spatial-inf-sci.net/V-3-2020/549/2020/", 
		src: "/images/thumbnails/academia-paper-2.jpg", 
		alt: "Restauration de cliché historique", 
		nature: "publication", 
		date: "Août 2020",
	},
	{
		title: "Deep learning for automatic colorization of legacy grayscale aerial photographs", 
		description: "Utilisation d'un réseau de neurones profond pour la colorisation automatique de photographies aériennes panchromatiques.", 
		href: "https://ieeexplore.ieee.org/document/9103274", 
		src: "/images/thumbnails/academia-paper-1.jpg", 
		alt: "Colorisation de cliché historique", 
		nature: "publication", 
		date: "Mai 2020",
	},
	{
		title: "La colorisation de photographies aériennes anciennes", 
		description: "Article de vulgarisation sur la colorisation automatique des photographies aériennes panchromatiques.", 
		href: "https://zaeu-strasbourg.eu/wp-content/uploads/2020/03/N11_colorisation.pdf", 
		src: "/images/thumbnails/academia-zaeu-1.jpg", 
		alt: "Extrait de l'article", 
		nature: "publication", 
		date: "Mars 2020",
	},
	{
		title: "La Géographie de Ptolémée", 
		description: "Outil interactif pour l'analyse des alignements maritimes extraits à partir de la Géographie de Ptolémée.", 
		href: "https://poterekq.github.io/ptolemy/", 
		src: "/images/thumbnails/academia-ptolemy-1.jpg", 
		alt: "Carte réalisée à partir de la Géographie de Ptolémée", 
		nature: "carte web", 
		date: "Mai 2019",
	},
	{
		title: "Le développement de techniques de colorisation automatique (Master 2)", 
		description: "Développement de méthodes d'apprentissage pour la colorisation automatique de produits aériens panchromatiques.", 
		href: "https://mega.nz/file/jtAnCY4B#wN4gsbsq6HPVieIdcqKN1TqsI7MKKcVG-x_rREJglI8", 
		src: "/images/thumbnails/master-dissertation-3.jpg", 
		alt: "Résultat de colorisation", 
		nature: "mémoire", 
		date: "Septembre 2018",
	},
	{
		title: "SIG géo-historique et dynamiques urbaines (Master 2)", 
		description: "Analyses des dynamiques urbaines dans la partie Nord de l'Eurométropole de Strasbourg depuis 1956.", 
		href: "https://mega.nz/file/jk4AkCgT#Z7pWLdEvLL76-jcDDqveyvCJN8OUcr-I0q-Y71yxb3k", 
		src: "/images/thumbnails/master-dissertation-2.jpg", 
		alt: "Typologie des îlots urbains", 
		nature: "mémoire", 
		date: "Février 2018",
	},
	{
		title: `Evaluation des produits "taches urbaines/artificialisées" existants (Master 1)`, 
		description: "Comparaison des apports et limites de produits d'occupation et d'usage du sol sur 6 métropoles françaises.", 
		href: "https://mega.nz/file/zpYFVZ7T#Qpmunxci7SS4r1JcWOwhIuLwIkvIiMMQn6v1HwF8SJM", 
		src: "/images/thumbnails/master-dissertation-1.jpg", 
		alt: "Carte d'accord spatial", 
		nature: "mémoire", 
		date: "Juillet 2017",
	},
	{
		title: "Artificialisation et ségrégation socio-spatiale (Master 1)", 
		description: "Outil de visualisation de la relation entre l'artificialisation des sols à Houston (Texas) et les données de census.", 
		href: "/work/master-presentation-1/index.html", 
		src: "/images/thumbnails/master-presentation-1.jpg", 
		alt: "Interface de visualisation des résultats", 
		nature: "carte web", 
		date: "Février 2017",
	},
	{
		title: "Résultats du prototype pour l'extraction des taches urbaines", 
		description: "Outil de visualisation des résultats de classification de la tache urbaine sur Strasbourg, à partir d'images SPOT.", 
		href: "https://poterekq.github.io/a2s-urban-webmap/", 
		src: "/images/thumbnails/academia-a2s-1.jpg", 
		alt: "Interface de visualisation des résultats", 
		nature: "carte web", 
		date: "Septembre 2016",
	},
]